apiVersion: v1
kind: ConfirMap
metadata:
  name: {{ include "animal-image-gen-and-store-appl.fullname" . }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k |indent 4}}: {{ $v | quote }}
  {{- end }}
